example/.umirc.ts, example/app.ts, example/pages/plugin-initial-state.js, packages/plugin-initial-state/src/utils/getModelContent.tsx
fix:  import getInitialState method
=> fix: initial-state does not import

packages/plugin-access/src/index.ts, packages/plugin-access/tests/index.test.ts
**变更：**
1. plugin-access 删除 showWarning 选项
=> feat: 删除 plugin-access 的 showWarnining 选项

example/.umirc.ts, example/pages/utils/index.tsx, packages/plugin-request/src/request.ts, packages/plugin-request/tests/useRequest.test.js, packages/plugin-utils/README.md, packages/plugin-utils/package.json, packages/plugin-utils/src/index.tsx, packages/preset-react/src/index.ts, yarn.lock
```json
{
"classnames": "^2.2.6",
"debug": "^4.1.1",
"js-cookie": "^2.2.1",
"lodash": "^4.17.15",
"moment": "^2.24.0",
"query-string": "^6.11.0",
"react-helmet": "^5.2.1"
}
···
=> feat: new umi plugin utils

packages/plugin-dva/src/dva.tpl, packages/plugin-dva/src/index.ts
微前端场景下不能自动销毁更新会引入一些额外的 bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/48)
=> feat: following the DvaContainer lifecycle to create/destroy dva instance

packages/plugin-locale/fixtures/singular/.umirc.ts, packages/plugin-locale/fixtures/singular/src/locale/en-US.js, packages/plugin-locale/fixtures/singular/src/locale/sk.js, packages/plugin-locale/fixtures/singular/src/locale/zh-CN.js, packages/plugin-locale/fixtures/singular/src/page/index.js, packages/plugin-locale/src/index.test.ts, packages/plugin-locale/src/index.ts, packages/plugin-locale/src/templates/locale.tpl, packages/plugin-locale/src/templates/runtime.tpl
=> feat: support title locale

packages/plugin-qiankun/src/slave/index.ts, packages/plugin-qiankun/src/slave/lifecycles.ts, packages/plugin-qiankun/src/slave/runtimePlugin.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/51)
=> chore(qiankun): optimize qiankun slave plugin

package.json, packages/plugin-analytics/src/index.test.ts, yarn.lock
=> fix: update umi version beta.32

example/.umirc.ts, example/app.ts, packages/plugin-layout/src/layout/index.tsx
同步之前的 https://github.com/umijs/plugin-layout/pull/1 这个修改
=> feat: layout support patchMenus runtime config

packages/plugin-model/src/helpers/executor.tsx
fix https://github.com/umijs/plugin-model/issues/28
=> fix: resolve warnings on React 16.13

packages/plugin-initial-state/fixtures/default/.umirc.ts, packages/plugin-initial-state/fixtures/default/src/app.js, packages/plugin-initial-state/fixtures/default/src/pages/index.js, packages/plugin-initial-state/fixtures/noEntry/.umirc.ts, packages/plugin-initial-state/fixtures/noEntry/src/app.js, packages/plugin-initial-state/fixtures/noEntry/src/pages/index.js, packages/plugin-initial-state/fixtures/noExports/.umirc.ts, packages/plugin-initial-state/fixtures/noExports/src/pages/index.js, packages/plugin-initial-state/package.json, packages/plugin-initial-state/src/index.test.ts, packages/plugin-initial-state/src/index.ts, packages/plugin-initial-state/src/utils/getModelContent.tsx, packages/plugin-initial-state/src/utils/index.ts, yarn.lock
fix: https://github.com/umijs/umi/issues/4027
=> fix: initial-state enable strategy

packages/plugin-layout/src/index.ts
=> fix: winPath problem in layout component path

packages/plugin-qiankun/README.md
2.0 版本计划做一些较大的改进 https://github.com/umijs/plugins/issues/64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/79)
=> chore(qiankun): update readme statement

example/.umirc.ts, packages/plugin-layout/package.json, packages/plugin-layout/src/index.ts, packages/plugin-layout/src/runtime.tsx.tpl
Changes:
1. 内置 plugin-antd-icon-config 插件到 plugin-layout 里
2. icon 支持 route.menu.icon 和 route.icon，前者优先级更高
cc @Ariel-Cheng @chenshuai2144 
Close #60 
Ref #81
=> feat: built-in plugin-antd-icon-config

packages/preset-ant-design-pro/README.md, packages/preset-ant-design-pro/package.json, packages/preset-ant-design-pro/src/index.ts
related: https://github.com/ant-design/ant-design-pro/pull/6039
=> feat: @umijs/preset-ant-design-pro

packages/plugin-block-devtool/src/index.ts
=> 🚑 hotfix: layoutConfig has default value

packages/plugin-analytics/src/fixtures/analytics-ga-key/.env, packages/plugin-analytics/src/fixtures/analytics-ga-key/.umirc.ts, packages/plugin-analytics/src/fixtures/analytics-ga-key/pages/index.less, packages/plugin-analytics/src/fixtures/analytics-ga-key/pages/index.tsx, packages/plugin-analytics/src/index.test.ts, packages/plugin-analytics/src/index.ts
增加环境变量 GA_KEY 来设置 ga。
@chenshuai2144 的需求
=> feat: 通过环境变量来设置 ga

package.json, packages/plugin-access/src/fixtures/normal/.umirc.ts, packages/plugin-access/src/fixtures/normal/access.ts, packages/plugin-access/src/fixtures/normal/pages/index.tsx, packages/plugin-access/src/index.test.ts, packages/plugin-access/src/utils/getAccessProviderContent.ts, packages/plugin-access/src/utils/getRootContainerContent.ts, packages/plugin-dva/src/index.test.ts, packages/plugin-initial-state/src/index.test.ts, packages/plugin-initial-state/src/index.ts, packages/plugin-initial-state/src/runtime.tsx.tpl, packages/plugin-initial-state/src/utils/getModelContent.tsx, packages/plugin-model/src/index.ts, packages/plugin-model/src/runtime.tsx.tpl, test/testUtils.ts, yarn.lock
* 修复因为 access 里依赖了 routes，导致用户修改任意代码，会触发页面 reload 的问题
* 调整 access, initial-state 和 model 的结构，适应单测的写法
* 补充 access 的单测
=> fix: access hmr

packages/plugin-request/src/request.ts, packages/plugin-request/tests/interceptors.test.js
close https://github.com/umijs/plugins/issues/90
=> feat: request plugin support interceptors

packages/plugin-dva/src/connect.tpl
Close #89
Ref #96
长期还是会走 ast 分析，和 dva 3 一起做。
=> fix: dva-loading types

packages/preset-ant-design-pro/src/index.ts
=> fix(preset-ant-design-pro): fix plugin no work bugs

packages/plugin-block-devtool/src/index.ts, packages/plugin-dva/src/dva.tpl, packages/plugin-initial-state/src/utils/getExportContent.tsx, packages/plugin-locale/src/templates/locale.tpl, packages/plugin-locale/src/templates/localeExports.tpl, packages/plugin-request/src/request.ts
忽略了一些 lint 错误
主要有两种
一种是 js 没带 ts 定义的
```
// @ts-ignore
import createLoading from '/Users/qixian/Documents/github/ant-design-pro/node_modules/dva-loading/dist/index.esm.js';
```
一种是 ts 定义错误的
```
// @ts-ignore
export const event = new EventEmitter();
// @ts-ignore
...(window.g_useSSR ? { initialState: window.g_initialData } : {}),
// @ts-ignore
history.push({
pathname: errorPage,
query: { errorCode, errorMessage },
});
```
=> 🚑 lint: igrone some plugin ts error

packages/plugin-dva/src/dva.tpl, packages/plugin-initial-state/src/utils/getExportContent.tsx, packages/plugin-locale/src/templates/localeExports.tpl
=> 🐛 bug: fix typescript error

example/models/bar.ts, example/pages/plugin-model.js, packages/plugin-model/package.json, packages/plugin-model/src/utils/getUseModelContent.ts, yarn.lock
remove lodash.isEqual dependency
=> chore: switch lodash.isEqual to fast-deep-equal

example/pages/plugin-initial-state.js, packages/plugin-initial-state/src/fixtures/setInitialState/.umirc.ts, packages/plugin-initial-state/src/fixtures/setInitialState/src/app.js, packages/plugin-initial-state/src/fixtures/setInitialState/src/pages/index.js, packages/plugin-initial-state/src/fixtures/setInitialState/test.js, packages/plugin-initial-state/src/index.test.tsx, packages/plugin-initial-state/src/utils/getModelContent.tsx, packages/plugin-model/src/runtime.tsx.tpl
related issue: https://github.com/umijs/umi/issues/4230
=> feat: setInitialState

packages/plugin-antd/src/index.ts
Close https://github.com/umijs/umi/issues/4315#issuecomment-606367942
=> fix: antd dark and compat mode

packages/plugin-qiankun/src/master/runtimePlugin.ts
透传otherConfigs
https://github.com/umijs/qiankun/issues/325#event-3170772708
=> fix: qiankun support other configs

packages/preset-ant-design-pro/src/chainWebpack.ts, packages/preset-ant-design-pro/src/index.ts
=> 🐲 config: less pro config

packages/plugin-dva/src/connect.tpl
=> fix(plugin-dva): add immer reducer type

packages/plugin-analytics/src/index.ts
Cannot read property 'baidu' of undefined
TypeError: Cannot read property 'baidu' of undefined
close https://github.com/ant-design/ant-design-pro/issues/6347
=> fix: api.userConfig.analytics is options

packages/plugin-qiankun/src/master/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/147)
=> fix(qiankun): 修复 qiankun 插件生成 mock 时 React undefined 的问题

packages/plugin-antd/src/index.ts
fix: https://github.com/ant-design/ant-design/issues/23154
=> fix(antd): missing default theme

packages/plugin-antd/package.json, packages/plugin-antd/src/index.ts, packages/plugin-layout/package.json, yarn.lock
Close https://github.com/umijs/plugins/pull/150
Close https://github.com/umijs/plugins/pull/140
ref: https://github.com/ant-design/ant-design/issues/23154
=> feat: antd support multiply themes

packages/plugin-layout/src/types/interface.d.ts
layout 的 hideMenu 和 hideNav 配置应该是可选的。
Close: https://github.com/umijs/next-app/issues/1
=> chore: types

packages/plugin-access/src/utils/runtimeUtil.ts, packages/plugin-layout/src/layout/index.tsx
- plugin-layout
- plugin-access 
-  #158
=> fix: render menu where initialState changed

packages/plugin-block-devtool/src/index.ts
=> fix(plugin-block-devtool): localesPath no found bug

packages/plugin-initial-state/src/utils/getModelContent.tsx
使用 useCallback 包裹 setInitialState & refresh
=> fix: add useCallback to initialState methods

example/app.tsx, packages/plugin-layout/src/layout/index.tsx, packages/plugin-layout/src/layout/useRightContent.tsx, packages/plugin-layout/src/types/interface.d.ts
rightRender 中添加 setInitialState 参数，使得可以根据 initialState 状态的变更，更新自定义布局
=> fix: layoutConfig-rightRender add setInitialState param #114

packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/master/modifyRoutes.ts, packages/plugin-qiankun/src/master/runtimePlugin.ts, packages/plugin-qiankun/src/slave/index.ts, packages/plugin-qiankun/src/types.ts
所有需要读取配置的行为都挪到 api.xxx 中通过 api.config 的方式读取
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/179)
=> feat(qiankun): 支持通过其他插件来懒启动 qiankun plugin

packages/plugin-layout/package.json, packages/plugin-layout/src/utils/getLayoutConfigFromRoute.ts, packages/plugin-layout/src/utils/getMenuFromRoute.ts
- remove memoize-one
修复由于修改路由导致的菜单渲染，页面不重新渲染问题。
=> feat(layout): remove memoize-one

packages/plugin-layout/src/index.ts, packages/plugin-layout/src/layout/index.tsx, packages/plugin-layout/src/layout/useRightContent.tsx, packages/plugin-layout/src/utils/getLayoutContent.tsx, packages/plugin-layout/src/utils/getMenuFromRoute.ts, packages/plugin-layout/test/__snapshots__/getMenuFromRoute.test.js.snap, packages/plugin-layout/test/getLayoutContent.test.js, packages/plugin-layout/test/getMenuFromRoute.test.js
```
export const layout = async ({ initialState }) => {
return {
rightRender: () => {
return <RightContent />;
},
collapsed: initialState?.collapsed,
footerRender: () => <Footer />
};
};
```
Close: https://github.com/umijs/plugins/issues/114
=> 💥 feat(plugin-layout): support runtimeConfig is a promise

packages/plugin-layout/src/layout/index.tsx
在 plugin 之前再嵌套一个 layou 就会出问题。我的插件就翻车了，应该使用 props 里面的而不是在全局找
=> fix(plugin-layout): fix Fix problems with nested layouts

packages/plugin-layout/package.json
=> ⚡️ fix(layout): peer pro-layout

packages/plugin-layout/src/layout/index.tsx
=> fix(layout): amend the hideFooter config

jest.config.js, packages/plugin-dva/src/index.ts
=> Revert "fix: change connect.ts name"

packages/plugin-helmet/src/index.ts, packages/plugin-helmet/src/templates/exports.tpl
修复 helmet 类型
Close https://github.com/umijs/plugins/pull/220
=> fix: helmet types

packages/plugin-dva/src/runtime.tpl
Close https://github.com/umijs/umi/issues/4726
=> fix: ctx should return

packages/plugin-helmet/src/templates/runtime.tpl
被编码问题
Close https://github.com/umijs/umi/issues/4727
=> chore: helmet cheerio encode

packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/slave/runtimePlugin.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/223)
=> feat(qiankun): 兼容 ssr

packages/plugin-layout/src/layout/index.tsx
close https://github.com/ant-design/ant-design-pro/issues/6661
=> fix(plugin-layout): fix menu.defaultOpen no work problem

packages/plugin-access-layout/src/AccessLayout.tpl, packages/plugin-access-layout/src/index.ts
修复 initialState 不生效的问题
修复 icon 重复引入问题
=> fix: @initialState no work

packages/plugin-locale/src/templates/SelectLang.tpl
* 修复引入所有antd icons 的问题
* 修复 locale 弹框位置不对的问题
=> fix(plugin-locale): fix locale bugs

packages/plugin-locale/src/index.ts, packages/plugin-locale/src/templates/SelectLang.tpl
```
iconsPkgPath: winPath(	
dirname(require.resolve('@ant-design/icons/package.json')),	
),
```
不需要这种丑代码了
=> feat(plugin-locale): do no use antd icon

packages/plugin-model/src/utils/getUseModelContent.ts
fix: 配置 update 函数后导致错误的重渲染
close #215
=> fix: the lastStateRef repeat setting (#229)

packages/plugin-locale/src/templates/locale.tpl, packages/plugin-locale/src/templates/localeExports.tpl
Guys, we still need this because there is no RTL yet in Ant Design Pro plus it's gonna be useful for any umi app
=> feat: RTL for pro [URGENT!!!] 

packages/plugin-qiankun/src/master/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/271)
=> fix(qiankun): 修复 babel parse ts 文件出错的问题

packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/275)
=> fix(qiankun): 支持异步启动 qiankun slave

packages/plugin-antd/src/index.ts, packages/plugin-antd/src/runtime.tpl
=> feat: don't filter antd.config.locale

packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/slave/index.ts, packages/plugin-qiankun/src/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/279)
=> feat(qiankun): 添加 shouldNotModifyDefaultBase slave 配置用于关闭默认修改行为

packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/284)
=> feat(qiankun): slave 默认启用 runtimeHistory

packages/plugin-dva/src/connect.tpl
=> fix(plugin-dva): add RequiredConnectProps

packages/plugin-layout/src/layout/index.tsx
close https://github.com/ant-design/ant-design-pro/issues/6907
=> fix(plugin-layout): fix rightContentRender no work problem

packages/plugin-model/src/helpers/executor.tsx
related #263 
@awmleer @brickspert 简单实现了一个油猴脚本可以记录 model 的值的变化。相当于一个 devTool.
目前就是粗暴的把更新记录写在 window 下面。帮忙 review 下这样有没有问题
=> feat: useModel dev 环境下的增加数据更新记录

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/289)
=> fix(qiankun): 修复 mounting 期间更新操作丢失 & 短时间内连续更新会抛状态异常的问题

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
上个 [PR](https://github.com/umijs/plugins/pull/296) 存在问题
=> fix(qiankun): concat not defined in MicroApp

package.json, packages/plugin-qiankun/examples/app2/pages/index.js, packages/plugin-qiankun/examples/app3/pages/$abc.js, packages/plugin-qiankun/examples/app3/pages/index.js, packages/plugin-qiankun/examples/master/models/base.js, packages/plugin-qiankun/package.json, packages/plugin-qiankun/src/master/MicroApp.tsx.tpl, packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/slave/index.ts, packages/plugin-qiankun/src/slave/lifecycles.ts, packages/plugin-qiankun/src/slave/runtimePlugin.ts, yarn.lock
依赖 https://github.com/umijs/umi/pull/5096 发布
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/312)
=> feat(qiankun): 支持运行时动态设置 clientRender 的 rootElement

packages/plugin-qiankun/src/slave/index.ts
变更点：
* 移除 api.modifyConfig，通过 api.modifyDefaultConfig 读取 `process.env.INITIAL_QIANKUN_SLAVE_OPTIONS` 统一设置初始值，后续都通过 api.config 读取插件配置
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/313)
=> chore(qiankun): optimize code login

packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/master/modifyRoutes.ts, packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/314)
=> fix(qiankun): fix slave options retire bug

packages/plugin-model/src/index.ts, packages/plugin-model/src/utils/getTmpFile.ts, packages/plugin-model/src/utils/index.ts, packages/plugin-model/tests/getName.test.ts, packages/plugin-model/tests/index.test.tsx
close #321 https://github.com/umijs/umi/issues/5195
=> refactor: rewrite getName to make it behave consistant in different envs

packages/plugin-qiankun/src/index.ts, packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/333)
=> feat(qiankun): expose plugin enable api

packages/plugin-esbuild/src/index.ts
=> fix: esbuild targets

packages/plugin-dva/src/index.ts
=> fix: dva model register duplicate

packages/plugin-locale/src/templates/SelectLang.tpl
- Remove whitespaces
- Update flag icon
=> Update SelectLang template

packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/353)
=> feat(qiankun): SOCKET_SERVER 环境变量支持通过 HOST 生成

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl, packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/359)
=> feat(qiankun): 支持运行时同时配置 master 和 slave

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl, packages/plugin-qiankun/src/slave/connectMaster.tsx.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/360)
=> fix(qiankun): 支持未开启 useModel 的场景

example/pages/plugin-initial-state.js, example/pages/plugin-model.js, packages/plugin-model/src/utils/getUseModelContent.ts
fix: 调用 model 中的 setState 后，立即切换页面，因为 setState 还没有生效，会导致新页面不能取到最新数据。
=> fix: update state failed when unmount component immediate after update

packages/plugin-qiankun/examples/master/.umirc.js, packages/plugin-qiankun/src/master/AntdLoader.tsx.tpl, packages/plugin-qiankun/src/master/MicroApp.tsx.tpl, packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/master/modifyRoutes.ts, packages/plugin-qiankun/src/slave/lifecycles.ts.tpl, packages/plugin-qiankun/typings/index.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/384)
=> feat(qiankun): 支持通过配置 autoSetLoading 自动开启 loading 动画

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl, packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/385)
=> fix(qiankun): 默认开启 loading 动画

packages/plugin-qiankun/examples/master/.umirc.js, packages/plugin-qiankun/src/master/modifyRoutes.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/386)
=> fix(qiankun): 修复配置序列化异常的问题

packages/plugin-qiankun/src/master/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/387)
=> chore(qiankun): 优化提示

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl, packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/394)
=> fix(qiankun): 自动 loading 默认关

packages/plugin-qiankun/src/master/modifyRoutes.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/402)
=> feat(qiankun): 兼容配置了 routeBindingAlias 同时又使用了原 microApp 的方式

packages/plugin-locale/package.json
=> chore: upgrade react-intl and intl

packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/404)
=> feat(qiankun): 兼容 webpack5

packages/plugin-layout/src/utils/intl.ts, yarn.lock
close https://github.com/ant-design/ant-design-pro/issues/7484
close https://github.com/ant-design/pro-components/issues/750
=> fix(layout): fix layout console some warning

packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/421)
=> fix(qiankun): 修复 slave 子应用独立运行时多创建了一个 history 导致的 业务 history.push 失效的问题

packages/plugin-qiankun/src/slave/slaveRuntimePlugin.ts.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/424)
=> fix(qiankun): 修复 clientRenderOpts 可能为空的问题

packages/plugin-access/src/utils/getAccessProviderContent.ts, packages/plugin-access/src/utils/runtimeUtil.ts, packages/plugin-access/tests/utils/__snapshots__/runtimeUtil.test.ts.snap, packages/plugin-access/tests/utils/runtimeUtil.test.ts
close https://github.com/ant-design/ant-design-pro/issues/7473
close https://github.com/ant-design/ant-design-pro/pull/6997
ref https://github.com/ant-design/ant-design-pro/issues/7478
=> fix(access): 修复因为可变数据导致的数据不同步的问题

packages/plugin-initial-state/src/index.ts, packages/plugin-initial-state/src/utils/getProviderContent.tsx
增加一个 initialStateConfig ，如果 initialState 需要很长时间才能请求回来，就可以展示一个兜底界面
=> feat(initialState): support initialStateConfig

.circleci/config.yml, .github/workflows/ci.yml, packages/preset-react/src/index.ts, packages/preset-react/src/react.ts, yarn.lock
ref: https://github.com/umijs/umi/pull/5690
=> feat: support React 17 new JSX syntax

packages/preset-react/src/react.ts
ref: https://github.com/umijs/plugins/pull/445
=> fix: react version undefined

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
close https://github.com/umijs/plugins/issues/434
=> fix: 我感觉name都变了的话,肯定要重新loadMicroApp啊

packages/plugin-layout/src/index.ts
close https://github.com/ant-design/ant-design-pro/issues/7705
close umijs/umi#5765
=> fix(layout): fix layoutExports no has error

packages/plugin-locale/src/index.ts, packages/plugin-locale/src/templates/localeExports.tpl
=> fix: localeInfo warning

packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/470)
=> fix(qiankun): 修复 runtimePublicPath 开发环境无法读取用户配置的 publicPath 的问题

packages/plugin-layout/src/index.ts, packages/plugin-layout/src/layoutExports.ts.tpl
Close https://github.com/umijs/umi/issues/5802
=> fix: layout exports

packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl, packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/479)
=> chore(qiankun): 旧版本配置方式从 warning 改成 error

packages/plugin-locale/src/templates/SelectLang.tpl
close https://github.com/ant-design/ant-design-pro/issues/6870
这么简单竟然也写错了
=> fix(locale): fix locale postLocalesData now work error

packages/preset-react/src/react.ts
=> fix: 修复在 React 17 下当不使用 ts 的情况下，启动项目仍然会提示更新 tsconfig.json 中 jsx 字段的问题

packages/plugin-locale/src/templates/SelectLang.tpl
close https://github.com/ant-design/ant-design-pro/issues/7875
=> fix(locale): support SelectLang props reload

packages/plugin-access/src/utils/runtimeUtil.tsx
Close https://github.com/umijs/umi/issues/5660
Close https://github.com/umijs/umi/issues/2319
=> fix: access runtimeUtil compact IE

packages/plugin-qiankun/src/common.ts, packages/plugin-qiankun/src/master/getMicroAppRouteComponent.ts.tpl, packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl, packages/plugin-qiankun/src/master/modifyRoutes.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/503)
=> feat(qiankun): 优化代码，移除运行时 require 方式引入模块

packages/plugin-locale/src/templates/SelectLang.tpl
close https://github.com/ant-design/ant-design-pro/issues/7940
=> fix(layout): fix SelectLang keys error

packages/plugin-qiankun/src/constants.ts, packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/481)
=> feat(qiankun): 移除子应用对 mountElementId 的变更

packages/plugin-locale/src/templates/locale.tpl
Close https://github.com/umijs/umi/issues/5704
=> fix(locale): unused return statement

packages/plugin-qiankun/src/common.ts, packages/plugin-qiankun/src/constants.ts, packages/plugin-qiankun/src/master/index.ts, packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/515)
=> feat(qiankun): 移除主应用对 mountElementId 的变更

packages/plugin-qiankun/src/common.ts, packages/plugin-qiankun/src/master/getMicroAppRouteComponent.ts.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/517)
=> fix: 修复启动阶段的 warning

packages/plugin-qiankun/src/master/getMicroAppRouteComponent.ts.tpl, packages/plugin-qiankun/src/master/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/518)
=> fix: 移除 webpack 构建时无效引用 warning

packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl, packages/plugin-qiankun/src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/531)
=> chore: 更新一些不推荐的配置的提示信息

packages/plugin-qiankun/src/slave/index.ts, packages/plugin-qiankun/src/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/536)
=> feat: 增加 devSourceMap 配置用于关闭开发阶段 sourcemap 插件

packages/plugin-lodash/README.md, packages/plugin-lodash/fixtures/normal/.umirc.ts, packages/plugin-lodash/fixtures/normal/src/pages/index.js, packages/plugin-lodash/package.json, packages/plugin-lodash/src/index.test.ts, packages/plugin-lodash/src/index.ts, packages/preset-react/package.json, packages/preset-react/src/index.ts
Ref: https://github.com/umijs/plugins/pull/535
=> feat(lodash): on demand loaded

packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
适配 `export const qiankun` 为异步函数的场景
=> fix: getSlaveRuntime

packages/plugin-qiankun/src/common.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/552)
=> feat: 支持微应用配置嵌套的子路由

packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl, packages/plugin-qiankun/src/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/560)
=> feat: 增加 credentials 参数，自动携带跨域 cookie

packages/plugin-layout/src/layout/index.tsx
menuItem should support target as documented
=> fix(layout): menuItem should support target

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl, packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
resolve https://github.com/umijs/plugins/issues/556
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/564)
=> fix: 修复 prefetch true 行为

packages/plugin-locale/src/templates/SelectLang.tpl
=> feat(locale): add 8px margin between icon and label for SelectLang

packages/plugin-model/src/helpers/executor.tsx
related https://github.com/umijs/umi/pull/6435
=> fix: ie11 useModel throw error on state changes

packages/plugin-locale/src/index.ts, yarn.lock
ref: https://github.com/umijs/plugins/commit/e6f56255b5df987030dd29468fa67d992036fb78#diff-750375f55b4a91d1832486ae6eb4948b8d322810342edc5a498e9809de3d4806R92
=> fix(locale): runtime plugin register order

packages/plugin-esbuild/src/index.test.ts, packages/plugin-esbuild/src/index.ts
https://github.com/umijs/plugins/pull/586
=> fix(esbuild): default target

packages/plugin-locale/src/index.ts, packages/plugin-locale/src/templates/localeExports.tpl
Revert https://github.com/umijs/plugins/pull/573
Close https://github.com/umijs/umi/issues/6451
=> fix(locale): emit dispatch rerender

packages/plugin-dva/src/dva.tpl, packages/plugin-dva/src/index.ts, packages/plugin-dva/src/runtime.tpl
Refs: https://github.com/umijs/plugins/pull/601, https://github.com/umijs/umi/pull/6463
Close: https://github.com/umijs/umi/issues/6404
Related: https://github.com/umijs/umi/pull/6500
Thanks @robinv8  !
=> fix(ssr): dva app ins conflict

packages/plugin-openapi/src/index.ts
Add some configurations supported by OpenAPI generator but not included in plugin-openapi.
=> feat(openapi): sync some extra props with openapi generator.

.github/workflows/outdated.yml
same as https://github.com/umijs/umi/pull/6066#issuecomment-765868637
=> chore: github action upgrade comment

packages/plugin-layout/src/layout/index.tsx
=> fix(layout): 修复 403 页面显示逻辑

packages/plugin-dva/src/connect.tpl
fix a ts type check problem: Type 'Dispatch' is not generic.ts. (ts: 2315) for #234
=> fix a ts type check problem. (ts: 2315) #234

packages/plugin-layout/src/index.ts
close https://github.com/ant-design/ant-design-pro/issues/8449
=> feat(layout): support layoutActionRef export

packages/plugin-access/src/index.ts, packages/plugin-access/src/utils/getAccessContent.ts, packages/plugin-access/tests/index.test.ts, packages/plugin-access/tests/utils/getAccessContent.test.ts, packages/plugin-layout/src/layout/index.tsx, packages/plugin-layout/src/utils/getLayoutContent.tsx
close https://github.com/ant-design/ant-design-pro/issues/8432
=> feat(plugin-access): fix traverseModifyRoutes

packages/plugin-locale/src/index.ts, packages/plugin-locale/src/templates/localeExports.tpl
修复 plugin-locale 在多个多语言插件时产生 imported 重复的错误
=> fix(plugin-locale): multilocale problem

packages/plugin-locale/src/index.ts, packages/plugin-locale/src/templates/localeExports.tpl
=> feat(plugin-locale): fix mfsu mode locale

packages/plugin-locale/src/utils.ts
fix https://github.com/ant-design/ant-design-pro/commit/965cf49783dd3391a67a76a8a67b96898ccd6852
=> fix(locale): fix antdLocale is null,mfsu will error

packages/plugin-initial-state/src/utils/getModelContent.tsx
close https://github.com/ant-design/ant-design-pro/issues/8403
=> feat(model): support setInitialState await 10ms time

packages/plugin-initial-state/src/utils/getModelContent.tsx
```tsx
const { initialState, setInitialState } = useModel('@@initialState');
setInitialState((s) => ({ ...s, currentUser: undefined }));
setInitialState({...initialState,currentUser: undefined})
```
=> feat(plugin-initial-state): support setInitialState params is function

packages/plugin-layout/src/layout/index.tsx.tpl
close https://github.com/ant-design/ant-design-pro/issues/8775
close https://github.com/ant-design/ant-design-pro/issues/8520
=> fix(layout): if currentPathConfig is null, render loading

packages/plugin-locale/src/templates/SelectLang.tpl, packages/plugin-locale/src/templates/localeExports.tpl, yarn.lock
close https://github.com/ant-design/ant-design-pro/issues/8244
=> fix(locale): changeLang will trigger rerender

example/.umirc.ts, packages/plugin-antd-dayjs/README.md, packages/plugin-antd-dayjs/package.json, packages/plugin-antd-dayjs/src/index.ts, packages/plugin-antd-dayjs/src/runtime.tpl, yarn.lock
使用 @umijs/plugin-antd-dayjs 替换 antd-dayjs-webpack-plugin
=> feat: add plugin dayjs

packages/plugin-antd/src/index.ts
增加 mobile 配置
```
antd: {
mobile: false
},
```
开启后
默认，或者mobile:true
Close: https://github.com/umijs/plugins/issues/696
=> feat: add config antd mobile:false

packages/plugin-request/src/request.ts
close https://github.com/ant-design/ant-design-pro/issues/9064#issuecomment-917807731
=> feat: BizError 返回 response

packages/plugin-stylus/README.md, packages/plugin-stylus/package.json, packages/plugin-stylus/src/index.ts
add package `@umijs/plugin-stylus`
=> feat(stylus): add package plugin-stylus.

packages/plugin-openapi/src/index.ts
close https://github.com/ant-design/ant-design-pro/issues/9247
=> fix(openapi): fix array config is null

packages/plugin-antd/src/index.ts
ref https://github.com/ant-design/ant-design/issues/32195
=> feat: support next antd version

packages/plugin-layout/src/layout/index.tsx.tpl, packages/plugin-layout/test/__snapshots__/index.test.jsx.snap, packages/plugin-model/src/index.ts
close https://github.com/ant-design/ant-design-pro/issues/9283
=> fix(layout): fix login render twice error

packages/plugin-antd/src/runtime.tpl
Modal and notification had remove prefixCls config in antd@4
=> fix(prefixCls): Modal and notification had remove prefixCls config in @antd4

packages/plugin-locale/src/templates/SelectLang.tpl
In my project I needed to add polish flag and language, also added custom icon if someone want to replace original
=> add: polish flag and language, custom icon

packages/plugin-layout/src/layout/index.tsx.tpl, packages/plugin-layout/src/layoutExports.ts.tpl
`childrenRender` 传入 `BasicLayoutProps`
=> feat: props with childrenRender

packages/plugin-antd-mobile/README.md, packages/plugin-antd-mobile/package.json, packages/plugin-antd-mobile/src/index.ts
Closes: https://github.com/umijs/plugins/issues/757
=> feat: add plugin-antd-mobile

packages/plugin-helmet/src/templates/runtime.tpl
**use SSR**, script in helmet can not output to html
source:
```html
<Helmet>
<script>console.log(123)</script>
</Helmet>
```
output:
```html
// there is no script
```
this PR would fix this problom
=> fix(helmet): add script tag in SSR

packages/plugin-qiankun/src/slave/connectMaster.tsx.tpl
=> fix:  Minimize the use of the lodash module

packages/plugin-dva/package.json
https://github.com/dvajs/dva/issues/2417
=> fix(dva): bumped dva-immer

packages/plugin-antd-mobile/src/index.ts
期望的配置是
```
{
antdMobile: {
hd: true
}
}
```
现在的实现是
```
hd:{ }
```
https://mobile.ant.design/zh/guide/hd
=> feat: describe antd-mobile config

packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
=> fix(plugin-qiankun) fix insert with microapp not work

packages/plugin-locale/src/templates/localeExports.tpl
=> fix: addLocale type

packages/plugin-analytics/src/index.ts
=> chore: add gtag for google analytic

packages/plugin-qiankun/src/slave/index.ts
在本地研发的逻辑里，如果从配置中检查到了当前应用为主应用，应该把入口 html 中的资源替换为本地资源
=> feat(plugin-qiankun): 支持 qiankun 主应用本地研发

packages/plugin-qiankun/package.json
- fix https://github.com/umijs/plugins/issues/879
=> chore(qiankun): remove unused peerDependencies

packages/plugin-qiankun/src/slave/index.ts
* ref https://github.com/umijs/umi/pull/11690
=> fix(qiankun): 线上环境忽略 mfsu 配置
