.gitignore
packages/@umijs/analytics/README.md
packages/@umijs/analytics/example/.umirc.js
packages/@umijs/analytics/example/pages/index.css
packages/@umijs/analytics/example/pages/index.js
packages/@umijs/analytics/package.json
packages/@umijs/analytics/src/index.ts

analytics for baidu tongji and google analytics
analytics for baidu tongji and google analytics
Configure in `.umirc.js`,
```js
export default {
plugins: [
['@umijs/analytics', {
ga:'google analytics code',
baidu: '5a66cxxxxxxxxxx9e13',
judge: ()=>true // true or false
}],
],
}
```
e.g `hm.src = "https://hm.baidu.com/hm.js?5a66c03cxxxxxx554f2b9e13";`
baidu is `5a66c03cxxxxxx554f2b9e13`
> 在JS中调用事件跟踪代码。
> `window._hmt.push(['_trackEvent', category, action, opt_label, opt_value]);`

feat: add plugin @umijs/plugin-analatics

---

example/.umirc.ts
example/app.ts
example/package.json
package.json
packages/plugin-layout/README.md
packages/plugin-layout/package.json
packages/plugin-layout/src/component/ErrorBoundary/index.tsx
packages/plugin-layout/src/component/Exception/index.less
packages/plugin-layout/src/component/Exception/index.tsx
packages/plugin-layout/src/index.ts
packages/plugin-layout/src/layout/index.tsx
packages/plugin-layout/src/layout/style.less
packages/plugin-layout/src/layout/useRightContent.tsx
packages/plugin-layout/src/locale/en-US.ts
packages/plugin-layout/src/locale/zh-CN.ts
packages/plugin-layout/src/types/index.d.ts
packages/plugin-layout/src/types/interface.d.ts
packages/plugin-layout/src/utils/getLayoutConfigFromRoute.ts
packages/plugin-layout/src/utils/getLayoutContent.tsx
packages/plugin-layout/src/utils/getMenuFromRoute.ts
packages/plugin-layout/src/utils/intl.ts
packages/plugin-layout/test/getLayoutConfigFromRoute.test.js
packages/plugin-layout/test/getLayoutContent.test.js
packages/plugin-layout/test/getMenuFromRoute.test.js
packages/plugin-layout/test/routes/normal.ts
packages/plugin-layout/test/routes/prefix.ts
packages/plugin-layout/test/routes/simple.ts
yarn.lock

feat: plugin-layout

---

packages/plugin-locale/src/locale.tpl

看了一下源码 
[RawIntlProvider ](https://github.com/formatjs/react-intl/blob/b207d805a9e5609983ac1b2ca8f9708030e12337/src/components/injectIntl.tsx#L17)是一个 React.createContext 的 Provider 对象
[IntlProvider  ](https://github.com/formatjs/react-intl/blob/b207d805a9e5609983ac1b2ca8f9708030e12337/src/components/provider.tsx)是一个包装了  RawIntlProvider  的组件，根据生命周期来进行更新
对于我们而言使用 RawIntlProvider  更加合理，问题应该是在别地方

 fix(locale): remove unuse IntlProvider

---

packages/plugin-locale/src/index.ts
packages/plugin-locale/src/locale.tpl
packages/plugin-locale/src/localeExports.tpl

加了一段复杂的if， 经测试，加载时序没有问题，node 端启动完成之后，intl已经存在，只要动态切换即可
```
// 如果全局的 g_intl 存在，且不是 setIntl 调用
if (g_intl && !changeIntl && !locale) {
return g_intl;
}
// 如果存在于 localeInfo 中
if (localeInfo[locale]) {
return createIntl(localeInfo[locale]);
}
// 不存在需要一个报错提醒
warning(
!!localeInfo[locale],
`The current popular language does not exist, please check the locale folder!`,
);
// 使用 zh-CN
if (localeInfo[DefaultLocale]) return createIntl(localeInfo[DefaultLocale]);
// 如果还没有，返回一个空的
return createIntl({
name: DefaultLocale,
messages: {},
});
```

bugfix: Fix the problem that the error will be reported when the language does not exist

---

packages/plugin-antd/src/index.ts

支持一键开启暗色主题：
```js
export default {
antd: {
dark: true
}
}
```
antd doc: https://github.com/ant-design/ant-design/pull/21668

feat: support antd dark 

---

package.json
packages/plugin-locale/docs/README.md
packages/plugin-locale/fixtures/runtime/.umirc.ts
packages/plugin-locale/fixtures/runtime/src/app.js
packages/plugin-locale/fixtures/runtime/src/locales/en-US.js
packages/plugin-locale/fixtures/runtime/src/locales/sk.js
packages/plugin-locale/fixtures/runtime/src/locales/zh-CN.js
packages/plugin-locale/fixtures/runtime/src/pages/index.jsx
packages/plugin-locale/src/index.test.ts
packages/plugin-locale/src/index.ts
packages/plugin-locale/src/templates/localeExports.tpl
yarn.lock

支持运行时对国际化做一些扩展与定制，例如自定义语言识别等。
自定义语言获取逻辑，比如识别链接 `?locale=${lang}` 当做当前页面的语言。
```js
// src/app.js
import qs from 'qs';
export const locale = {
getLocale() {
const { search } = window.location;
const { locale = 'zh-CN' } = qs.parse(search, { ignoreQueryPrefix: true });
return locale;
},
}
```
自定义语言切换逻辑。其中有三个参数：
- lang: 需要切换的语言
- realReload: 是否需要刷新页面，这个是由页面调用 `setLocale(lang, true)` 透传。
- updater：是否触发组件 rerender 重渲染。
```js
// src/app.js
export const locale = {
setLocale({ lang, realReload, updater }) {
history.push(`/?locale=${lang}`);
updater();
}
}
```

feat: locale polyfill and runtime config

---

packages/plugin-analytics/src/index.ts

chore: if analytics false, return

---

packages/plugin-dva/src/connect.tpl

命名空间“React”没有已导出的成员“ForwardRefRenderFunction”。

fix: 没有import react

---

example/.umirc.ts
example/app.ts
package.json
packages/plugin-request/src/request.ts
packages/plugin-request/tests/adaptor.test.js
packages/plugin-request/tests/antd.test.js
packages/plugin-request/tests/createTestServer.js
packages/plugin-request/tests/normal.test.js
packages/plugin-request/tests/useRequest.test.js
yarn.lock

类似之前的 https://github.com/umijs/plugin-request/pull/12
不能直接在模块初始化的时候去初始化运行时配置，当用户的 app.ts 中依赖了该文件的情况下就该模块的初始化时间就会被提前，无法获取到运行时配置。

fix: request runtime config not work in sometimes

---

packages/plugin-antd/src/index.ts

ant-design/ant-design#22068
Usage: https://github.com/ant-design/ant-design/blob/dad364c7f24a486ec54f38e741b5f1a81f9c105a/docs/react/customize-theme.en-US.md#use-dark-or-compact-theme

feat: 🆕 Add compact theme config to plugin-antd

---

packages/plugin-access/src/index.ts
packages/plugin-access/src/utils/getAccessProviderContent.ts
packages/plugin-access/src/utils/runtimeUtil.ts
packages/plugin-access/tests/__mocks__/fs.ts
packages/plugin-access/tests/index.test.ts
packages/plugin-access/tests/utils/getAccessProviderContent.test.ts
packages/plugin-access/tests/utils/runtimeUtil.test.ts

**变更：**
1. 在生成基本的路由权限后，再检查一遍子路由的存在与可访问性。当所有子路由存在且不可访问时，父路由也不可访问
Close https://github.com/umijs/umi/issues/4171

特性：当所有子路由存在且不可访问时，父路由也不可访问

---

packages/plugin-initial-state/src/utils/getModelContent.tsx

开发者自己调用`initial-state`的`refresh`方法时，`access`会收到中间状态，但这个是不合理的。`access.ts`中应该永远只拿到结果

fix: prevent unexpected undefined value passed to subsequent process

---

packages/plugin-antd/src/index.ts

https://github.com/umijs/umi/issues/4315#issuecomment-606367942
重现仓库：https://github.com/ewqazxc/umiDemo
`colorPalette is not defined`
https://unpkg.com/antd@4.1.0/dist/compact-theme.js 文件里有 color 的变量。

fix: compact mode throw error

---

packages/plugin-qiankun/examples/app1/.umirc.js
packages/plugin-qiankun/examples/app1/layouts/index.js
packages/plugin-qiankun/examples/app2/app.js
packages/plugin-qiankun/package.json
packages/plugin-qiankun/src/__tests__/common.test.ts
packages/plugin-qiankun/src/__tests__/mock/index.ts
packages/plugin-qiankun/src/common.ts
packages/plugin-qiankun/src/index.ts
packages/plugin-qiankun/src/master/index.ts
packages/plugin-qiankun/src/master/runtimePlugin.ts
packages/plugin-qiankun/src/slave/index.ts
packages/plugin-qiankun/src/types.ts

* 支持使用 rootExports.ts
* 支持传入 shouldNotModifyPublicPath 参数来关闭 qiankun 注入的 runtimePublicPath
* 修复路由正则匹配过于精确的问题
* 子应用 props 中注入 getMatchedBase 方法用于获取当前匹配到的动态前缀
* 增加 keepOriginalRoutes 配置保持应用原路由信息
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/138)

feat(qiankun): merge 1.x features to 2.x

---

packages/plugin-antd/src/index.ts

fix: dark and compact conflict

---

.fatherrc.ts

Close: https://github.com/umijs/next-app/issues/8
引入 plugin-layout 插件导致全量引入 antd
配置前 umi 3.09MB antd 2.88MB
配置后 umi 2.07MB antd 774.34KB

feat: Import on Demand Antd

---

example/.umirc.ts
packages/plugin-layout/src/utils/getMenuFromRoute.ts

之前为了兼容老得写法，所以配置了 name 就等同于配置了 menu，优先级高于 menu：false。
然后存在 menu 为 false 时，name 仍用于 document.title 等用途的场景，所以调高优先级，menu 显示指定为 false 时，不在侧边栏中展示，与文档保持一致。
Close https://github.com/umijs/umi/issues/4179

fix: 修复 layout 配置 menu 显示指定为 false 不生效 

---

packages/plugin-antd/package.json
packages/plugin-antd/src/index.ts

ref: https://github.com/ant-design/ant-design/pull/23171
Closes https://github.com/umijs/plugins/pull/159, https://github.com/umijs/umi/issues/4513
4.1.3 使用了 `getThemeVariables` 来做混合模式配置，以后这部分工作让 antd 那边的 `getThemeVariables` 来做比较好。

fix: update antd theme plugin config

---

packages/plugin-qiankun/package.json
packages/plugin-qiankun/src/index.ts
packages/plugin-qiankun/src/master/index.ts
packages/plugin-qiankun/src/slave/index.ts

将 qiankun 的 master 和 slave 作为两个独立的子插件注册到 qiankun 插件，从而使得其他插件可以通过 modifyConfig 方法唤起 qiankun 插件。

fix(qiankun): 拆分 qiankun 配置加载

---

example/app.tsx
example/locales/nl-NL.js
packages/plugin-locale/docs/README.md
packages/plugin-locale/package.json
packages/plugin-locale/src/index.ts
packages/plugin-locale/src/templates/SelectLang.tpl

locale 插件支持导出 <Selectlang/> 组件
选择语言的展示组件。可以通过开启 locale 插件，从 umi 中获取该组件。只有当项目依赖 antd, 同时项目 /locales 文件夹下有超过两个语言文件时才会显示。可配置的属性有：
- langUIConfig, 默认包含 "简体中文" 、"繁体中文"、 "英文" 三种语言配置,当需要展示其他语言时，可以通过配置 langUIConfig 来扩展，格式如下所示。
- globalIconClassName, 全球图标的样式。
- <[Dropdown/](https://ant.design/components/dropdown-cn/#API)> 的所有 API。
```tsx
import { SelectLang } from 'umi';
<SelectLang
langUIConfig={[{
lang: 'nl-NL', // 语言的 key 与 antd & locales 下的文件名保持一致
label: 'Nederlands', // 下拉菜单中展示的语言名
icon: '🇳🇱', // 下拉菜单中展示的 icon （一般为国旗
title: 'Taal', // 鼠标浮上全球图标时展示的文案（一般为“语言”这个词的各种翻译
}]}
>
```

feat(locale): export Selectlang component

---

jest.config.js
packages/plugin-dva/src/index.ts

多个 export * from model  会导致 ts 的同名冲突，
改成d.ts个可以使用 skipLibCheck 跳过检查，不影响目前的功能。

fix: change connect.ts name

---

packages/plugin-access-layout/README.md
packages/plugin-access-layout/package.json
packages/plugin-access-layout/src/AccessLayout.tpl
packages/plugin-access-layout/src/LayoutContent.tpl
packages/plugin-access-layout/src/LayoutModel.tpl
packages/plugin-access-layout/src/components.tpl
packages/plugin-access-layout/src/docs/README.md
packages/plugin-access-layout/src/index.ts
packages/plugin-access-layout/src/utils/index.ts
packages/plugin-access-layout/src/utils/runtimeUtil.ts

> 根据我上一次提到的方案，整合实现为 Umi@3 的插件。简单的试用了一下，发现几乎可以满足所有的需求，而且在我看来应该是理解成本最低的方案。
使用 npm:
```bash
$ npm install --save-dev @umijs/plugin-access-layout
```
或者使用 yarn:
```bash
$ yarn add @umijs/plugin-access-layout --dev
```
这个插件将 plugin-access 和 plugin-layout 插件的功能整合在一起，为了支持 Umi 的约定式用法，还有更多的动态设置方案。
1、支持约定式和配置式
2、动态修改权限
3、动态使用菜单
4、支持运行时配置 Pro-Layout
5、支持页面级别配置 Pro-Layout
6、支持页面级权限
7、支持页面级修改权限
8、支持不使用 Pro-layout
9、兼容 Pro 旧项目的写法
1、配套 plugin-locale 使用，会默认开始国际化的菜单
2、配合 plugin-model 使用，可以使用 useModel('@@accessLayout')
3、配合 plugin-initial-state 使用，可以不指定权限判断数据
```ts
accessLayout: {
iconNames: ['smile'], // 约定式用法，需要将所有用到的 icon 名称写全，为了按需加载
useModel: true, // 声明是否搭配了 plugin-model 使用
}
```
```ts
export const accessLayout = {
title: "Runtime Demo",
// Pro-Layout 支持的所有配置
}
```
```ts
useEffect(() => { …
```

feat: add plugin-access-layout

---

packages/plugin-access-layout/src/AccessLayout.tpl
packages/plugin-access-layout/src/index.ts

当 config 中配置 locale 时，会自动使用国际化菜单。可以通过组件中的 props hasLocale 或者 runtime 中的配置修改。

feat: support plugin-locale

---

packages/plugin-antd/src/index.ts
packages/plugin-antd/src/runtime.tpl

增加配置 config，详细配置请查看 https://ant.design/components/config-provider-cn/
（合并后再添加文档）
```
antd:{
config:ConfigProviderProps
}
```
注意：locale 配置无效，会提示用户使用 @umijs/plugin-locale
Close: https://github.com/ant-design/ant-design-pro/issues/6742

feat: support ConfigProcider

---

packages/plugin-helmet/fixtures/normal/src/app.js
packages/plugin-helmet/fixtures/ssr/src/app.js
packages/plugin-locale/src/index.ts

处理 Close [umi 引入 ant.design全家桶时icons无法配置按需加载造成单包超过3M](https://github.com/umijs/umi/issues/4823) 引起的 icons 全量引入问题

fix: antd icons all in bundle when enable locale antd 

---

packages/plugin-access-layout/src/AccessLayout.tpl
packages/plugin-access-layout/src/LayoutModel.tpl
packages/plugin-access-layout/src/index.ts

相关 Issues https://github.com/ant-design/ant-design-pro/pull/6758
1、默认开启，通过配置关闭
2、useModel 配置，可以通过检测plugin-model 是否使用来自动开关
3、需要提供一个配置来控制，使用配置式路由，并且自定义 layout。即使用配置式不使用运行时的场景。便于更早的 pro 项目做升级。
4、动态菜单数据从 `useModel('@@accessLayout')` 中获取 menu 值，配置式使用的时候，需要留一个口子，在当前配置菜单的基础上修改。
可能是 除了 menu 再指定一个 menu 的修改函数，默认是直接替换。 如 props.renderMenuData
```
const { menu:serveMenu } = useModel('@@accessLayout');
const renderMenuData = props.renderMenuData || (a,b)=>b;
const localeMenu = props.menuData || props.routes;
const menu = renderMenuData(localeMenu,serveMenu);
```

feat: support serve menu

---

packages/plugin-model/src/utils/getUseModelContent.ts

**问题原因**：
将 lastState 赋值给 useRef<any>(state)，就会让 lastState 和 state 同步数据，当 state 变化后 lastState 的值也会跟着变，然后在下面的第 3 行处又手动将当前的新值赋值给 lastState, 就会导致会不重新 render
``` ts
1 if (!isEqual(ret, lastState.current)) {
2 lastState.current = ret;
3  setState(ret);
4 }
```
PS:  这个地方为了代码可读性，更改了一下变量命名
issue refs: https://github.com/umijs/plugins/issues/215

fix: the lastStateRef repeat setting

---

packages/plugin-locale/src/templates/locale.tpl
packages/plugin-locale/src/templates/localeExports.tpl

Add direction support to plugin-local, so the direction attribute can be determined and
passed to ConfigProvider, the main purpose behind this effort is to add RTL support
in ant design pro, issue #6599 in ant design pro repo

feat:Add direction support to plugin-local [URGENT!!!]

---

packages/plugin-layout/src/index.ts
packages/plugin-layout/src/runtime.tsx.tpl

Close: https://github.com/umijs/umi/issues/4483
支持旧的写法
```
{
path: '/',
component: '@/pages/index',
menu: { // 兼容此写法
name: '欢迎',
icon: 'smile',
}
}
```

fix: menu icon inoperative

---

packages/plugin-preact/package.json

dependencies 中增加对 preact-compat 的依赖要求以修复 #192

fix: (plugin-preact) fix #192

---

packages/plugin-preact/package.json

Reverts umijs/plugins#265
preact 10 开始不需要 preact-compat 的。

Revert "fix: (plugin-preact) fix #192"

---

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl

MicroApp 支持配置 lifeCycles
```jsx
<MicroApp 
name="app1" 
lifeCycles={{
beforeLoad: (_, global) => { global._value= 123 }
}}
/>
```

feat(qiankun): MicroApp support lifeCycles

---

packages/plugin-qiankun/src/slave/lifecycles.ts

Close https://github.com/umijs/plugins/issues/233
ref: https://github.com/umijs/umi/pull/4979  ，单独发不受 umi callback 影响
子应用默认情况下，会自动处理 loading
如果子应用需要精准控制 loading，通过
```ts
// app.ts
export const qiankun = {
slave: {
// 关闭自动 loading
autoSetLanding: false
}
}
```
在子应用页面中，单独调用 `setLoading`
```tsx
// pages/Bar.tsx
import React from 'react';
import { useModel } from 'umi';
export default () => {
const { setLoading } = useModel('@@qiankunStateFromMaster');
React.useEffect(() => {
setLoading(false);
}, []);   
...
}
```

chore(qiankun): microApp auto setLoading

---

packages/plugin-qiankun/src/slave/index.ts
packages/plugin-qiankun/src/slave/lifecycles.ts

- 支持基于 `props.container` 查找 `mountElementId` 并传入 umi 的 render，用于限定子应用 mount 节点的查找范围
- umijs/umi#5067

feat(qiankun): support to pass container for different sub apps

---

packages/plugin-locale/src/templates/SelectLang.tpl

Solved #317 Issue
Added default config map to the Languages supported by Antd. 
- Languages list: [Antd Internationalization](https://ant.design/docs/react/i18n)
- Text translated with Google Translate
- Enclosed Alphanumeric Supplement from wikipedia: [Enclosed Alphanumeric Supplement](https://en.wikipedia.org/wiki/Enclosed_Alphanumeric_Supplement)
- Native Names for languages: [List of ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

Added Antd Languages support

---

packages/plugin-layout/src/layout/index.tsx

面包屑导航栏默认的跳转方式是a标签，当history使用hash时，面包屑导航栏跳转错误
close https://github.com/ant-design/pro-components/issues/156

渲染Breadcrumb 子节点,使用Link标签

---

packages/plugin-dva/src/index.ts

Close #339
eg.
```
import ModelFooBar0 from '/private/tmp/sorrycc-Jd7VZW/models/foo-bar.ts';
import ModelFoo1 from '/private/tmp/sorrycc-Jd7VZW/models/foo.ts';
import ModelModel2 from '/private/tmp/sorrycc-Jd7VZW/pages/bar/model.ts';
import ModelModel3 from '/private/tmp/sorrycc-Jd7VZW/pages/foo/model.ts';
```

fix(dva): upperCamelCase model's default specifier

---

packages/plugin-layout/src/layout/renderRightContent.tsx
packages/plugin-layout/src/layout/style.less

pro-layout 6.x 版本的 mix 模式头部默认是黑底，添加 `anticon` className 是的头部文字可以自适应为白色。
另外修复了 name 左边缺少 margin 的问题。

fix: add anticon className to layout right content for support pro-layout mix mode

---

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl

Add props export for `MicroApp` component, to fix `MicroAppProps` missing bug in `MicroAppWithMemoHistory` component: https://github.com/umijs/plugins/blob/747e0e7b5a4e7b99c253457c2c852c73b1ec7021/packages/plugin-qiankun/src/master/MicroAppWithMemoHistory.tsx.tpl#L2

fix(qiankun): type missing in MicroAppWithMemoHistory

---

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
packages/plugin-qiankun/src/master/MicroAppWithMemoHistory.tsx.tpl
packages/plugin-qiankun/src/slave/lifecycles.ts.tpl

1. 支持通过 `historyRef` 来获取子应用的 history 实例，进而在外层控制子应用路由切换
2. `MicroAppWithMemoHistory` 内置组件支持响应 `url` 参数的变化去修改 子应用的 history

feat(qiankun): support to access history ref for slave

---

packages/plugin-qiankun/src/common.ts

✔ Webpack
Compiled successfully in 43.77s
WARNING  Compiled with 1 warnings                                                                                    2:38:48 ├F10: PM┤
warning  in ./src/.umi/plugin-qiankun/common.ts
"export 'default' (imported as 'pathToRegexp') was not found in 'path-to-regexp'

fix: fix a warning when build plugin qiankun

---

package.json
packages/plugin-qiankun/src/master/modifyRoutes.ts
yarn.lock

* MicroApp 和 React 不使用 cjs 的方式引入，cjs 会影响提速方案的实施
* 相关 pr: https://github.com/umijs/umi/pull/5456
* 依赖 umi@3.2.21（已发布）
* packages/plugin-qiankun/examples 下的例子已验证

fix(qiankun): no cjs require, use umiExports.MicroApp

---

packages/plugin-qiankun/package.json
packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
packages/plugin-qiankun/src/slave/slaveRuntimePlugin.ts.tpl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/418)

feat(qiankun): 支持一屏展示多个 umi 应用渲染实例

---

packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
packages/plugin-qiankun/src/slave/slaveRuntimePlugin.ts.tpl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/423)

fix(qiankun): remount 时 import 的 history 为旧的 history

---

packages/plugin-qiankun/src/slave/qiankunModel.ts.tpl

#426 这里每次重新挂载子应用时都会从 initState 初始化，然而这个 initState 只在首次挂载才会被赋值，在之后切换过来时则直接作为 useState 的初始值
close #426

fix #426 useModel 父子应用通信无法在切换应用时保持最新的全局数据

---

packages/plugin-qiankun/src/slave/index.ts

`shouldNotModifyDefaultBase` 从 `userConfig` 进行读取，确保用户可以通过配置项关闭默认 `routerBase`

fix(qiankun): cannot disable default router base via config

---

packages/plugin-preact/package.json
packages/plugin-preact/src/index.ts

在最新的 `umi@^3.2.28` 中使用 `plugin-preact` 启动会报如下错误：
```shell
$ umi dev
Cannot find module 'preact-compat/lib/create-react-class'
Require stack:
- /Users/username/projectname/node_modules/@umijs/plugin-preact/lib/index.js
```
因为 `preact@10` 以后 core 包中已经包含 compat 了，所以不存在 preact-compat 这个包，猜测可能是遗留的代码
移除对应的 alias 后，项目可以正常启动并打包
另： 将 preact 升级到了最新的版本

fix: remove broken webpack alias in plugin-preact

---

packages/plugin-esbuild/package.json
packages/plugin-esbuild/src/index.ts
yarn.lock

换成 [esbuild-loader](https://github.com/privatenumber/esbuild-loader)，主要 [esbuild-webpack-plugin](https://github.com/sorrycc/esbuild-webpack-plugin) 有下面几点：
1、两个 esbuild 实例不会退出（Client build + Server build 的时候）
2、esbuild 未更新到最新版本

feat: using esbuild-loader

---

packages/plugin-qiankun/src/common.ts
packages/plugin-qiankun/src/constants.ts
packages/plugin-qiankun/src/master/index.ts
packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl

This reverts commit d5e140c7
有主应用 umi3 子应用 umi2 的场景，移除了 root-master 就会导致 umi2 子应用直接渲染到主应用的根节点了..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/516)

Revert "feat(qiankun): 移除主应用对 mountElementId 的变更 (#515)"

---

packages/plugin-locale/src/templates/locale.tpl

close https://github.com/umijs/plugins/issues/532

fix: useLayoutEffect will be warning in ssr mode

---

packages/plugin-locale/src/templates/localeExports.tpl

when has runtimeLocale.setLocale setLocale not work

fix: when has runtimeLocale.setLocale setLocale not work

---

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl

bundled all lodash into `umi.js`

fix(qiankun): lodash bundled all

---

packages/plugin-openapi/src/index.ts

close https://github.com/ant-design/ant-design-pro/issues/8205

feat(openapi): support openAPIConfig is array

---

packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl

umi 自动生成的路由：
```javascript
export function getRoutes() {
const routes = [
{
"path": "/",
"component": require('yourProject/src/.umi/plugin-setting-drawer/SettingDrawer.tsx').default,
"routes": [
{
"path": "/",
"component": require('yourProject/src/.umi/plugin-layout/Layout.tsx').default,
"routes": [
{
"path": "/",
"component": require('@/layouts/index').default,
"routes": [
{
"path": "/home",
"component": require('@/pages/home').default,
"exact": true
}
]
}
]
}
]
}
];
```
src/app.ts 中添加的 qiankun 配置：
```
export const qiankun = fetch('/config').then(({ apps }) => {
return {
apps,
routes: [
{
path: '/app1',
microApp: 'app1',
}    
]
}
});
```

fix(qiankun): runtime routes not loaded correctly

---

packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl

This reverts commit ea086eef
revert https://github.com/umijs/plugins/pull/541 ，不兼容根路由是叶子节点的场景

Revert "fix(qiankun): runtime routes not loaded correctly (#541)"

---

packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl

resolve https://github.com/umijs/plugins/pull/563
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/plugins/565)

fix: 修复运行时路由不支持嵌套根路由的问题

---

packages/plugin-esbuild/src/fixtures/es5/.umirc.ts
packages/plugin-esbuild/src/fixtures/es5/src/pages/index.js
packages/plugin-esbuild/src/fixtures/normal/src/pages/index.js
packages/plugin-esbuild/src/index.test.ts
packages/plugin-esbuild/src/index.ts

Close https://github.com/evanw/esbuild/issues/1060

fix(esbuild): minify exposes target config for es5 projects

---

packages/plugin-esbuild/src/index.ts

[esbuild#pure](https://esbuild.github.io/api/#pure)
Support remove console.
```ts
export default {
esbuild: {
target: 'es5',
pure: ['console.log'],
},
};
```
+ [#7012](https://github.com/ant-design/ant-design-pro/issues/7012)
+ [#5266](https://github.com/ant-design/ant-design-pro/issues/5266)
+ [#3766](https://github.com/ant-design/ant-design-pro/issues/3766)
+ [#6540](https://github.com/ant-design/ant-design-pro/issues/6540)

feat(esbuild): exposes minify pure config

---

packages/plugin-dva/src/dva.tpl
packages/plugin-dva/src/index.ts

Was trying to use the mapset features of immer in my project, but got error that saying enableMapSet() need to be called when initializing the project. After further investigation, found out that enableAllPlugins is already exported from dva-immer but hasn't been supported to use in plugin-dva, so I made this change to resolve the issue I had.

feat: plugin dva support config immer.enableAllPlugins

---

packages/plugin-esbuild/src/fixtures/no-es5/.umirc.ts
packages/plugin-esbuild/src/fixtures/no-es5/src/pages/index.js
packages/plugin-esbuild/src/index.test.ts
packages/plugin-esbuild/src/index.ts

使用config里的targets自动配置ESBuildMinifyPlugin的target。
也算修复targets为ie时，esbuild默认target却是es2015，导致dist文件包含模板字符串报错的问题。
添加了no-es5的测试。其中测试normal和es5的结果不应是模板字符串，修改了。
fix umijs/umi#6359

feat(esbuild): apply userconfig targets to esbuild

---

packages/plugin-esbuild/package.json
packages/plugin-esbuild/src/index.ts

esbuild-loader不支持pure设置字段。
升级到2.9.2是因为2.10.0之后ESBuildPlugin被deprecated，build的时候有个提示log不太好看。
umijs/umi#6422

fix(esbuild): rm pure setting & bump esbuild-loader to 2.9.2

---

packages/plugin-layout/src/component/logo.tsx

When using v5 of ant-design-pro to run "npm run tsc", the following error will appear:
import React from 'react';
^
'React' is declared but its value is never read.(ts6133)

fix(layout): add React.FC to fix "React declared but never read" of "tsc --noEmit"

---

packages/plugin-locale/src/index.ts
packages/plugin-locale/src/templates/locale.tpl

https://github.com/umijs/plugins/blob/2b2c169/packages/plugin-locale/src/templates/locale.tpl#L67

fix(plugin-locale): default antd locale use esm

---

packages/preset-umi2-compatible/src/plugins/router/router.ts

目前mfsu还不支持自动处理export *导出 ,   [#6922](https://github.com/umijs/umi/issues/6922) 。
router 不支持导出 : [umijs](https://github.com/umijs/umi/blob/master/packages/preset-built-in/src/plugins/generateFiles/core/umiExports.ts#L11)

fix(preset-umi2-compatible): 支持 mfsu

---

packages/plugin-qiankun/src/common.test.ts
packages/plugin-qiankun/src/common.ts
packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl

feat: support insert route

---

packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl

比如运行时路由配置的是：
```diff
routes: [
{ path: '/app1', microApp: 'app1' },
+ { path: '/app2', routes: [
+   { path: '/app2/nest', microApp: 'app2' }
+ ] },
]
```

feat: 支持运行时配置嵌套的路由关联微应用

---

packages/plugin-locale/src/templates/localeExports.tpl

去掉 setLocale的语言key 的正则校验
通过 [addLocale](https://umijs.org/zh-CN/plugins/plugin-locale#addlocale) 动态添加语言，
但无法通过 [setLocale](https://umijs.org/zh-CN/plugins/plugin-locale#setlocale) 无法使用，因为 setLocale 对语言的  key 做检验。
目前的  lang key的定义 其实是多样化的，比如 zh-Hant、zh-Hans ....
```
{
"iso_code":"zh-Hant",
"alt_name":"zh-Hant",
"name":"Chinese Traditional",
"id":2
},
{
"iso_code":"zh-Hans",
"alt_name":"zh-Hans",
"name":"Chinese Simplified",
"id":5
},
```

feat: No verification of lang-key

---

packages/plugin-antd/src/index.ts

我们最近在做主题功能，看到了antd已经支持了动态主题：https://ant.design/docs/react/customize-theme-variable-cn   
但是如文档所说，需要去除 babel-plugin-import，否则打包后由于css顺序问题，variable的css可能被覆盖导致主题不生效  
故希望新增一个disableBabelPluginImport配置项，主动设置为true时，不对antd使用babel-plugin-import，来使用antd的动态主题功能

feat: add config antd disableBabelPluginImport:false

---

packages/plugin-locale/src/templates/SelectLang.tpl

Polish language was missing in the config map, rendering was innacurate.

Polish added to the list of language config map

---

packages/preset-react/src/defaultConfig.ts

这段代码会导致在用户仅设置了某个插件的个别配置后，该插件的所有默认配置都失效
```ts
import { IApi, IConfig } from '@umijs/types';
export default (api: IApi) => {
const defaultOptions = {
access: {},
...api.userConfig,
} as IConfig;
api.modifyDefaultConfig((memo) => {
return {
...memo,
...defaultOptions, // 此操作会覆盖掉已 merge 的 config，强行使用 userConfig
};
});
};
```

fix(preset-react): 修复 modifyDefaultConfig 覆盖了配置问题

---

packages/plugin-locale/src/templates/SelectLang.tpl

Dropdown 的 placement 参数，在 RTL 时, bottomRight 其实并不会自动显示成 bottomLeft。
原来没有问题，是因为有 [autoAdjustOverflow](https://github.com/ant-design/ant-design/commit/235ab32f44d9594c59e00bff5bd114ad3e49d456) 选项，但是如果显示不溢出的话，这个 dropdown 的位置仍然是错的。
因为 autoAdjustOverflow 似乎在 antd 4.17 后的某个版本被关闭了(master 分支已经加回去了 https://github.com/ant-design/ant-design/commit/235ab32f44d9594c59e00bff5bd114ad3e49d456 )，所以暴露了这个问题。

feat(locale): 完善 RTL 支持

---

packages/plugin-dva/src/index.ts
packages/plugin-locale/src/index.ts

- close https://github.com/umijs/umi/issues/7000
解决了打包产物包含绝对路径的问题，我在app.ts和 plugin-dva遇到了，然后在issue里发现还有已知的plugin-locale
plugin-dva和plugin-locale在这个MR解决，另外两个在umi的仓库提交PR解决https://github.com/umijs/umi/pull/7983

fix(plugin-dva|plugin-locale): fix addRuntimePlugin use absolute path

---

packages/plugin-layout/src/index.ts
packages/plugin-layout/src/layout/style.less

更新 `style/index.less` 中引入 antd 默认主题变量的方式，避免报错：
```bash
Compile Error ：“Variable @root-entry-name is undefined”
```
ref: https://github.com/ant-design/ant-design/issues/33853

fix(layout): root-entry-name variable error

---

packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
packages/plugin-qiankun/src/master/index.ts
packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl

修复 使用 pnpm 安装 umi 依赖，项目启动时，.umi 目录下，plugin-qiankun 的临时文件部分依赖找不到
[#issues](https://github.com/umijs/umi/issues/8148)

fix(plugin-qiankun): fixed pnpm installation dependency error

---

packages/plugin-esbuild/src/index.ts

修复 esbuildminifyplugin  压缩导致的async，spread语法被作为全局变量设置到window上而引起的重复问题

修复minify导致的语法命名冲突问题

---

packages/preset-react/package.json

Bigfish 3 一直在使用 `@umijs/preset-react@1.8.x`，但目前最新版锁定了 `@umijs/plugin-locale@0.15.1`，不包含 `cookieEnable` 检查的修复，在无痕浏览器下仍然访问 `LocalStorage` 可能会报错（取决于浏览器配置）
单独切出 `preset-react-1.x` 分支，升级到 `@umijs/plugin-locale@0.15.2`，该版本仅包含这个修复 PR：https://github.com/umijs/plugins/pull/809

fix(preset-react): use locale 0.15.2 for check cookieEnable

---

packages/preset-react/package.json

`@umijs/preset-react@1.8.31` 的变更和 tag 都不在 GitHub 仓库里，通过 unpkg.com 对比产物做了手动恢复，以便继续 patch 发版

chore(preset-react): restore lost changes for 1.8.31
